# Generated by Django 2.2 on 2019-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='NOT DONE', max_length=255),
        ),
    ]
